import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
import { MoonLoader } from "react-spinners";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [input, setInput] = useState("");
  const [error, setError] = useState(false); // [error, setError
  const [output, setOutput] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (input.length < 30) setError(false);
  }, [input]);

  const submit = async () => {
    if (input.length > 30) return setError(true);
    setLoading(true);
    try {
      const res = await fetch("/api/marketing-copy", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ input }),
      });
      const data = await res.json();
      setOutput(data.result);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto py-12">
        <h2 className="text-2xl font-bold text-center pb-3">
          Marketing Copy Generator
        </h2>

        {/* input field for marketing copy */}
        <div className="flex flex-col gap-4 justify-center w-1/3 mx-auto">
          <div className="relative w-full">
            {error && (
              <p className="pt-1 text-red-500 text-xs">
                Character Limit Exceeded
              </p>
            )}
            <textarea
              className="w-full border-2 border-grey-300 big-white p-4 rounded-lg text-sm focus:outline-none resize-none"
              onChange={(e) => setInput(e.target.value)}
              value={input}
              rows={3}
              placeholder="Enter your topic here"
            />
            <div
              className={`absolute ${
                input.length > 30 ? "text-red-500" : "text-gray-400"
              } bottom-2 right-2 text-xs`}
            >
              <span>{input.length}/30</span>
            </div>
          </div>
          <button
            type="button"
            onClick={submit}
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          >
            {loading ? (
              <div className="flex gap-4 justify-center item-center">
                <p>Loading</p>
                <MoonLoader size={20} />
              </div>
            ) : (
              "Generate"
            )}
          </button>

          {/* output field for marketing copy */}
          {output && (
            <div className="mt-8 ">
              <h4 className="text-lg font-semibold pb-2">
                Your Marketing Copy:
              </h4>
              <div className="relative w-full rounded-md bg-gray-100 p-4 ">
                <p className="text-sm text-gray-700">{output}</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
